services:
  log:
    container_name: elk
    build: ./ELK-log/
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "7777:7777/udp"
  db:
    container_name: database
    image: postgres
    ports:
      - '${DB_PORT_HOST}:${DB_PORT}'
    volumes:
      - data:/data/db
      - ./database/initialization.sh:/docker-entrypoint-initdb.d/initialization.sh
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
volumes:
  data: { }